version: '3'

services:

  ffmpeg:
    build: ./Dockerfiles/ffmpeg
    container_name: ffmpeg
    links:
      - "rtmpserver"
    depends_on:
      - "rtmpserver"
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      webcam-network:
        ipv4_address: 172.23.2.3
        aliases:
          - ffmpeg


  rtmpserver:
      build: ./Dockerfiles/rtmpserver
      container_name: nginxRTMP
      ports:
        - 1935:1935
        - 8080:1936
      restart: unless-stopped
      volumes:
        - ./stream:/stream/hls
        - ./live:/stream/live
      networks:
        webcam-network:
          ipv4_address: 172.23.2.2
          aliases:
            - rtmpserver

networks:
  webcam-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.2.0/24

